_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("combined_xview_instance_segmentation_dataset_train",)
  TEST: ("combined_xview_instance_segmentation_dataset_val",)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.5
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "./outputs/output_localization_10"
TEST:
  EVAL_PERIOD: 5000
