_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("combined_xview_instance_segmentation_dataset_train",)
  TEST: ("combined_xview_instance_segmentation_dataset_val",)
DATALOADER:
  NUM_WORKERS: 2
MODEL:
  WEIGHTS: "./weights/model_final_2d9806.pkl"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "./outputs/output_localization_08"
TEST:
  EVAL_PERIOD: 5000
